export const colors = {
    black: '#000',
    blueishBlack: '#2E3E5C',
    blue: '#3E5481',
    green: '#BADA55',
    lightGreen: '#E5FF91',
    offWhite: '#F8F8F8',
    offWhiteOpacity: '#F8F8F899',
    white: '#FFFFFF',
    gray: '#9FA5C0',
    shadowGray: '#ccc',
    lightGray: '#EAEAEA',
    darkGray: '#afafaf',
    borderColor: '#D0DBEA',
    fadeBlack: '#4D4D4D',
    modalColor: '#1C1C1C',
    borderWhite: '#D0DBEA',
    parrot: '#BADA55',
    red: 'red',
  };